# Server Configuration for Render
server.port=${PORT:8080}
server.address=0.0.0.0

spring.application.name=chatbotBackend

# Database Configuration 
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?prepareThreshold=0
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# PGVector Configuration
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536

# Chat Generation (Groq)
spring.ai.openai.api-key=sk-dummy-key-to-pass-validation
spring.ai.openai.chat.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.api-key=${GROQ_API_KEY}
spring.ai.openai.chat.options.model=llama-3.1-8b-instant

# Vector Embedding (OpenRouter)
spring.ai.openai.embedding.base-url=https://openrouter.ai/api/v1
spring.ai.openai.embedding.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.embedding.options.model=text-embedding-3-small